### PR TITLE
Star/favorite notes

### LINKED ISSUE #10: Star the notes
screen shot 0029-09-06 at 1 36 21 am

### PR DESCRIPTION
**Pull request by robbawebba**
This Pull request allows users to "star" notes to mark them as favorites. Users are also able to filter notes to only display notes that are favorited. 

Closes #10

### CODE REVIEW

**Comment by kazup01** [comment]
Thanks for your great contribution! @robbawebba

**Comment by robbawebba** [comment]
@kazup01 Thank you for your patience! I think this code is ready for a full review now 👍 please request any changes you would like to see and I would be happy to update the PR 😄

**Comment by kazup01** [comment]
Thanks @robbawebba :)

**Comment by robbawebba** [comment]
Thanks @kazup01 and @kohei-takata! Let me know if you need any more help from the community! I'd love to stay involved 😄 I'll be checking the issues periodically too

**Pull request merged**
